source 'https://rubygems.org'


gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'bcrypt', '~> 3.1.7'
gem 'faker'
gem 'rspec-rails'
gem 'shoulda-matchers'
gem 'factory_girl'

group :development, :test do
gem 'simplecov', :require => false, :group => :test
  gem 'byebug'
end

group :development do
  gem 'web-console'

  gem 'spring'
end

