# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80b5bd6f017280786771bee04382df221cc9ad633487258cc9859c1abe7546e7d753708bbbee13d51feca39c9e49c24cbe4c18480d3d0079806c2dd1a9965f0d

test:
  secret_key_base: 5b4ee7ad4ce8b225103b235c74e8b0ac8040e7100fb237422c0eb735ee17fe84648d750c8fa423c1ecaa7866a311ccac42e775dc4d9862d8ed9555a8dcb7285d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
